export const suggestions = [
    { title: 'All', link: 'https://www.youtube.com' },
    { title: 'Music', link: 'https://www.youtube.com' },
    { title: 'Mixes', link: 'https://www.youtube.com' },
    { title: 'Trailer music', link: 'https://www.youtube.com' },
    { title: 'Soundtracks', link: 'https://www.youtube.com' },
    { title: 'Podcasts', link: 'https://www.youtube.com' },
    { title: 'Thoughts', link: 'https://www.youtube.com' },
    { title: 'Comedy clubs', link: 'https://www.youtube.com' },
    { title: 'Classical music', link: 'https://www.youtube.com' },
    { title: 'Indoor games and sports', link: 'https://www.youtube.com' },
    { title: 'Weight training', link: 'https://www.youtube.com' },
    { title: 'Ambient music', link: 'https://www.youtube.com' },
    { title: 'Playlists', link: 'https://www.youtube.com' },
    { title: 'Debates', link: 'https://www.youtube.com' },
    { title: 'Gaming', link: 'https://www.youtube.com' },
    { title: 'Live', link: 'https://www.youtube.com' },
    { title: 'Computer science', link: 'https://www.youtube.com' },
    { title: 'Combat sports', link: 'https://www.youtube.com' },
    { title: 'Recently uploaded', link: 'https://www.youtube.com' },
    { title: 'Watched', link: 'https://www.youtube.com' },
    { title: 'New to you', link: 'https://www.youtube.com' },    
]